### ISSUE TITLE
KiCAD 8.0.1: Commits are not sent to GitHub

### ISSUE THREAD

**Issue by tormyvancool** [adamws/kicad-git#4]
The pluginopens the interface.
But when I commit changes, fo GIT is regularly done while changes are NOT sent to GitHub.
Indeed when I go on GitHub to check if everything is ok, it isn't.

NOTE: why doesn't the plugin show up on the Schematic page?
![image](https://github.com/adamws/kicad-git/assets/32305535/5bbf04d1-f135-4b45-83e6-0234cc87597a)

**Comment by tormyvancool** [comment]
> 1. if you want to upload to remote you need to push (and not just commit)
> 2. plugins are limited to pcbnew, this is how KiCad does it

I can't commit without staging
After have stgaged I can commit. It turn itself off 
If I restart it, there is nothing

If it was working how it should I had not to open an issue here.

Here teh animated GIF
![KiCAD_Commit](https://github.com/adamws/kicad-git/assets/32305535/0a08f698-ce66-4827-a348-a5ae7b48278c)

**Comment by adamws** [comment]
`kicad-git` is just a launcher of git gui (https://git-scm.com/docs/git-gui)
- check if committing/pushing with CLI works
- check if working with `git gui` outside KiCad context works - if it doesn't - then this problem is not related to this plugin and git gui itself.
Closest I could find is this:
https://stackoverflow.com/questions/34547935/github-push-error-cant-read-some-heads-tracking-no-such-variable

**Comment by adamws** [comment]
did you tried changing config? apparently `git citool` does not behave same as `git gui`

**Comment by tormyvancool** [comment]
> did you tried changing config? apparently `git citool` / `git gui citool` does not behave same as `git gui`

So the GIT GUI external one (not in KiCAD) a syou saw it works.
For the "config.ini" you asked for: I have made it but it didn't change any behavior

**Comment by tormyvancool** [comment]
Version 0.3 issue solved. It Commits and pushes.
